models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $auth_key
 * @property integer $confirmed_at
 * @property string $unconfirmed_email
 * @property string $password_reset_token
 * @property integer $blocked_at
 * @property string $registration_ip
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $flags
 */
class User extends ActiveRecord implements IdentityInterface
{
    public $password_reset_token; 
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            // [['confirmed_at', 'blocked_at', 'created_at', 'updated_at', 'last_auth', 'flags'], 'integer'],
            // [['username'], 'string', 'max' => 25],
            // [['email', 'unconfirmed_email', 'last_useragent'], 'string', 'max' => 255],
            // [['password'], 'string', 'max' => 60],
            // [['auth_key'], 'string', 'max' => 32],
            // [['registration_ip'], 'string', 'max' => 45],
            [['username'], 'unique'],
            // [['email'], 'unique'],
            // [['email'], 'email'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Password'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'confirmed_at' => Yii::t('app', 'Confirmed At'),
            'unconfirmed_email' => Yii::t('app', 'Unconfirmed Email'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'blocked_at' => Yii::t('app', 'Blocked At'),
            'registration_ip' => Yii::t('app', 'Registration Ip'),
            'created_at' => Yii::t('app', 'Created At'),
            'last_auth' => Yii::t('app', 'Last Auth'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'last_useragent' => Yii::t('app', 'Last Useragent'),
            'flags' => Yii::t('app', 'Flags'),
        ];
    }

        /** INCLUDE USER LOGIN VALIDATION FUNCTIONS**/
        /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
 
/* removed
    public static function findIdentityByAccessToken($token)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
*/
    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'reset_password' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return password_verify($password, $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        return Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        return Yii::$app->security->generateRandomString() . '_' . (time() + 3600*24);
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->reset_password = null;
    }
    /** EXTENSION MOVIE **/

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->auth_key = \Yii::$app->security->generateRandomString();
                $this->created_at = time();
                $this->registration_ip = Yii::$app->request->getUserIp();
            }
            return true;
        }
        return false;
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\User;
use app\models\Files;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class UserController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $user = '';
        if (!\Yii::$app->user->isGuest) {
            $user = Yii::$app->getUser()->getIdentity(false);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/user');
        }
        return $this->render('index', [
            'model' => $model,
            'user' => $user,
        ]);
    }

    public function actionRegistration() 
    {
        if(Yii::$app->getRequest()->getIsAjax()) {
            $post = $_POST;
            $model = new User();
            $model->username = $post['login'];
            $model->name = $post['name'];
            $model->email = $post['email'];
            $model->password = $model->setPassword($post['password']);
            if($model->save()) {
                $message = "Спасибо за регистрацию, ваши данные:<br>";
                $message .= "Логин: " . $post['login'] . '<br>';
                $message .= "Пароль: " . $post['password'];

                Yii::$app->mail->compose()
                    ->setFrom('info@f-f.bz')
                    ->setTo($post['email'])
                    ->setSubject('Регистрация МЭК')
                    ->setHtmlBody($message)
                    ->send();
                return true;
            }
                
        }
    }

    public function actionForget()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new User;
        $type = '';
        $message = '';
        $type_password = '';
        if(isset($_POST['forget'])) {
            $query = $model->findByEmail($_POST['email']);
            $token = $model->generatePasswordResetToken();
            $query->reset_password = $token;
            if($query->save()) {
                $type = "forget";

                $message = "Здравствуйте! Для вашего email был инициирован процесс восстановления пароля. Если это были не вы, то игнорируйте это письмо.<br><br>";
                $message .= "Для продолжения просьба перейти по ссылке<br>";
                $message .= "http://test.rfrank.ru/user/forget?token=" . $token;

                Yii::$app->mail->compose()
                    ->setFrom('info@f-f.bz')
                    ->setTo($_POST['email'])
                    ->setSubject('Восстановление пароля – МЭК')
                    ->setHtmlBody($message)
                    ->send();
            }
        }

        if(isset($_GET['token']) && $model->findByPasswordResetToken($_GET['token'])) {
            if(isset($_POST['forget_password'])) {
                $update = $model->findByPasswordResetToken($_GET['token']);
                $update->password = $model->setPassword($_POST['password']);
                $update->removePasswordResetToken();
                if($update->save()) {
                    $message = 'Пароль изменен. Информация отправлена на ваш email.';
                    $mail = "Ваш пароль изменен, данные для входа:<br>";
                    $mail .= "Логин: " . $update->username . '<br>';
                    $mail .= "Пароль: " . $_POST['password'];

                    Yii::$app->mail->compose()
                        ->setFrom('info@f-f.bz')
                        ->setTo($update->email)
                        ->setSubject('Изменение пароля – МЭК')
                        ->setHtmlBody($mail)
                        ->send();
                }
            }
            
        } else {
            $type_password = "new_password";
        }
        

        return $this->render('forget', [
            'type' => $type,
            'type_password' => $type_password,
            'message' => $message,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect('/user');
    }

    public function actionFiles($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect('/user');
        }
        $model = new Files;
        $category = array('1' => 'Типовые документы', 'Отчетная информация', 'Аналитика', 'Интернет-трейдинг');
        $model = $model->find()->where(['is_visible' => 1, 'id_category' => $id])->all();
        return $this->render('files', [
            'model' => $model,
            'category' => $category,
        ]);
    }
}

views/user/files.php
<?php
use yii\helpers\Html;
use app\helpers\YiiHelper;

$this->title = $category[$_GET['id']] . ' | ' . $this->context->module->name;
?>

<div class="row">
	<div class="col-sm-9 col-sm-push-3 r">
		<div class="text">
			<h1><?= $category[$_GET['id']] ?></h1>
			<? if(!empty(YiiHelper::getTextblock("files_category_" . $_GET['id']))): ?>
				<p class="big"><?= YiiHelper::getTextblock("files_category_" . $_GET['id']) ?></p>
			<? endif; ?>
			<div class="docs">
				<div class="row">
					<div class="col-xs-6">
						<? foreach($model as $key => $file): 
						   $doc = 'files/files/'.$file->id.'/'.$file->file;
						?>
							<? if($key % 2 == 0): ?>
								<div class="one">
									<div class="title"><a href="/<?=$doc?>" rel="blank"><?= $file->title ?></a></div>
									<div class="meta"><?= pathinfo($doc, PATHINFO_EXTENSION) ?>, <?= str_replace(".", "," , strval(round(filesize($doc)/1024))) ?> кб</div>
								</div>
							<? endif; ?>
						<? endforeach; ?>
					</div>
					<div class="col-xs-6">
						<? foreach($model as $key => $file): 
						   $doc = 'files/files/'.$file->id.'/'.$file->file;
						?>
							<? if($key % 2 == 1): ?>
								<div class="one">
									<div class="title"><a href="/<?=$doc?>" rel="blank"><?= $file->title ?></a></div>
									<div class="meta"><?= pathinfo($doc, PATHINFO_EXTENSION) ?>, <?= str_replace(".", "," , strval(round(filesize($doc)/1024))) ?> кб</div>
								</div>
							<? endif; ?>
						<? endforeach; ?>
					</div>
				</div>
			</div>
        </div>
	</div>
	<?php echo \Yii::$app->view->renderFile('@app/views/layouts/_left_menu_file_sidebar.php'); ?>
</div>

views/user/forget.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-sm-9 col-sm-push-3 r">
		<div class="text">
			<h1>Клиентам</h1>
			<p class="big">Восстановления доступа к&nbsp;закрытым разделам сайта.</p>
			<div class="clients">
				<div class="row">
					<div class="col-xs-6">
						<div class="login">
							<? if(isset($_GET['token'])): ?>
								<? if(!empty($type_password) && $type_password == 'new_password'): ?>
									<p>Истёк срок действия кода для восстановления пароля. <a href='/user/forget'>Попробуйте восстановить пароль ещё раз</a></p>
								<? else: ?>
									<? if(!empty($message)): ?>
										<?= $message ?>
									<? else: ?>
										<form action="/user/forget?token=<?= $_GET['token'] ?>" method="post">
											<div class="one"><input type="text" autofocus placeholder="Новый пароль" name="password" id=""></div>
											<div class="one submit"><input type="submit" name="forget_password" value="Изменить" class="btn"></div>
										</form>
									<? endif; ?>
								<? endif; ?>
							<? else: ?>

								<? if(!empty($type) && $type == 'forget'): ?>
									<p>На ваш email отправлено письмо с инструкцией.</p>
								<? else: ?>
									<form action="/user/forget" method="post">
										<div class="one"><input type="text" autofocus placeholder="email" name="email" id=""></div>
										<div class="one submit"><input type="submit" name="forget" value="Отправить" class="btn"></div>
									</form>
								<? endif; ?>
							<? endif; ?>


						</div>
					</div>
				</div>
			</div>

        </div>
	</div>
	<?php echo \Yii::$app->view->renderFile('@app/views/layouts/_left_menu_file_sidebar.php'); ?>
</div>

views/user/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Клиентам | ' . $this->context->module->name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-sm-9 col-sm-push-3 r">
		<div class="text">
			<h1>Клиентам</h1>
			<? if(empty($user)): ?>
				<p class="big">Для получения доступа к&nbsp;закрытым разделам сайта вам&nbsp;необходимо&nbsp;авторизоваться</p>
				<div class="clients">
					<div class="row">
						<div class="col-xs-6">
							<div class="login">
								<?php $form = ActiveForm::begin([
								        'id' => 'login-form',
								        'options' => ['class' => 'form-horizontal'],
								        'fieldConfig' => [
								            'labelOptions' => ['class' => 'col-lg-1 control-label'],
								        ],
							    	]); 
							    ?>
							        <div class="one"><?= $form->field($model, 'username')->label('') ?></div>
							        <div class="one"><?= $form->field($model, 'password')->label('')->passwordInput() ?></div>
									<div class="one submit"><?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?> <span class="forget"><a href="/user/forget">Напомнить пароль</a></span></div>
							    <?php ActiveForm::end(); ?>
					
							</div>
						</div>
						<div class="col-xs-6">
							<div class="register">
								<h3>Завести аккаунт</h3>
								<p>Если вы&nbsp;хотите получить доступ к&nbsp;закрытым разделам сайта, вам необходимо завести аккаунт, корректно заполнив все поля формы.</p>
								<p><a href="" class="btn" data-popup="popup_register">Завести аккаунт</a></p>
							</div>
						</div>
					</div>
				</div>
				<div class="popup text mfp-hide" id="popup_register">
					<h2>Завести аккаунт</h2>
					<form id='registration'>
						<div class="one"><input type="text" placeholder="ФИО" name="name" id="name" class=" name required"></div>
						<div class="one"><input type="text" placeholder="Логин" name="login" id="login" class=" login required"></div>
						<div class="one"><input type="password" placeholder="Пароль" name="password" id="password" class=" password required"></div>
						<div class="one"><input type="text" placeholder="Email" name="email" id="email" class="email required"></div>
	                    <div id="reg-submit" class="one submit"><input id="reg" type="button" value="Отправить запрос" class="btn"></div>
					</form>
				</div>
			<? else: ?>
				<p class="big">Здравствуйте, <?= $user->name ?>. (<a href="/user/logout">Выход</a>)</p>

			<? endif; ?>
        </div>
	</div>
	<?php echo \Yii::$app->view->renderFile('@app/views/layouts/_left_menu_file_sidebar.php'); ?>
</div>